export const KEY_GENERATION_START = 'KEY_GENERATION_START'
export const KEY_GENERATION_ERROR = 'KEY_GENERATION_ERROR'
export const KEY_GENERATION_SUCCESS = 'KEY_GENERATION_SUCCESS'

export const SET_PASSPHRASE_SUCCESS = 'SET_PASSPHRASE_SUCCESS'

export const LEGACY_KEY_GENERATION_START = 'LEGACY_KEY_GENERATION_START'
export const LEGACY_KEY_GENERATION_ERROR = 'LEGACY_KEY_GENERATION_ERROR'
export const LEGACY_KEY_GENERATION_SUCCESS = 'LEGACY_KEY_GENERATION_SUCCESS'

export const WIF_KEY_GENERATION_START = 'WIF_KEY_GENERATION_START'
export const WIF_KEY_GENERATION_ERROR = 'WIF_KEY_GENERATION_ERROR'
export const WIF_KEY_GENERATION_SUCCESS = 'WIF_KEY_GENERATION_SUCCESS'

export const PRIVATE_KEY_GENERATION_START = 'PRIVATE_KEY_GENERATION_START'
export const PRIVATE_KEY_GENERATION_ERROR = 'PRIVATE_KEY_GENERATION_ERROR'
export const PRIVATE_KEY_GENERATION_SUCCESS = 'PRIVATE_KEY_GENERATION_SUCCESS'

export const SEG_WIT_KEY_GENERATION_START = 'SEG_WIT_KEY_GENERATION_START'
export const SEG_WIT_KEY_GENERATION_ERROR = 'SEG_WIT_KEY_GENERATION_ERROR'
export const SEG_WIT_KEY_GENERATION_SUCCESS = 'SEG_WIT_KEY_GENERATION_SUCCESS'

export const QR_CODE_GENERATION_START = 'QR_CODE_GENERATION_START'
export const QR_CODE_GENERATION_ERROR = 'QR_CODE_GENERATION_ERROR'
export const QR_CODE_GENERATION_SUCCESS = 'QR_CODE_GENERATION_SUCCESS'
